// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Untitled', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Untitled', async function() {
    await driver.get("http://localhost:4200/login")
    await driver.manage().window().setRect({ width: 1382, height: 744 })
    await driver.findElement(By.xpath("//input")).click()
    await driver.findElement(By.css(".form-group:nth-child(1) > .form-control")).sendKeys("adel@gmail.com")
    await driver.findElement(By.css(".btn")).click()
    {
      const element = await driver.findElement(By.xpath("//span"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.id("taillePull")).click()
    {
      const dropdown = await driver.findElement(By.id("taillePull"))
      await dropdown.findElement(By.xpath("//option[. = 'XXL']")).click()
    }
    await driver.findElement(By.css(".btn-primary > span")).click()
    await driver.executeScript("window.scrollTo(0,1785)")
    await driver.findElement(By.css(".img-circle")).click()
    await driver.findElement(By.linkText("Déconnexion")).click()
    await driver.findElement(By.css(".ng-valid")).sendKeys("adel@gmail.com")
    await driver.findElement(By.xpath("//div[2]/input")).sendKeys("123456")
    await driver.findElement(By.css(".form-group:nth-child(1) > .form-control")).click()
    await driver.findElement(By.css(".form-group:nth-child(1) > .form-control")).sendKeys("admin@admin.com")
    await driver.findElement(By.css("span")).click()
    {
      const element = await driver.findElement(By.xpath("//span"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css("tr:nth-child(4) .fa-eye")).click()
    await driver.findElement(By.css(".modal")).click()
    await driver.findElement(By.css("tr:nth-child(4) .checkbox")).click()
    await driver.findElement(By.css(".ng-untouched:nth-child(2)")).click()
    {
      const dropdown = await driver.findElement(By.css(".ng-untouched:nth-child(2)"))
      await dropdown.findElement(By.xpath("//option[. = 'Validé']")).click()
    }
    await driver.findElement(By.css(".form-control > span")).click()
    await driver.findElement(By.css("tr:nth-child(4) .fa-user")).click()
    await driver.close()
  })
})
