// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Default Suite', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Test', async function() {
    await driver.get("http://localhost:4200/login")
    await driver.findElement(By.xpath("//input[@type=\'email\']")).sendKeys("admin@admin.com")
    await driver.findElement(By.xpath("//input[@type=\'password\']")).sendKeys("123456")
    await driver.findElement(By.xpath("//button[contains(.,\'Login\')]")).click()
    await driver.findElement(By.linkText("My profile")).sendKeys("My profile")
    await driver.findElement(By.linkText("My profile")).click()
    await driver.findElement(By.name("TaillePull")).click()
    {
      const dropdown = await driver.findElement(By.name("TaillePull"))
      await dropdown.findElement(By.xpath("//option[. = 'L']")).click()
    }
    await driver.findElement(By.id("valider")).click()
  })
})
